export default {
  mainPage: ['animals', 'feelings', 'clothes', 'actions', 'food', 'weather', 'hollydays', 'objects'],
  pageAnimals: [
    {
      id: 0,
      word: 'cat',
      translation: 'кошка',
      image: 'img/cat.png',
      audioSrc: 'sounds/cat.mp3',
    },
    {
      id: 1,
      word: 'dog',
      translation: 'собака',
      image: 'img/dog.png',
      audioSrc: 'sounds/dog.mp3',
    },
    {
      id: 2,
      word: 'bird',
      translation: 'птица',
      image: 'img/bird.png',
      audioSrc: 'sounds/bird.mp3',
    },
    {
      id: 3,
      word: 'fish',
      translation: 'рыба',
      image: 'img/fish.png',
      audioSrc: 'sounds/fish.mp3',
    },
    {
      id: 4,
      word: 'mouse',
      translation: 'мышь',
      image: 'img/mouse.png',
      audioSrc: 'sounds/mouse.mp3',
    },
    {
      id: 5,
      word: 'chick',
      translation: 'цыпленок',
      image: 'img/chick.png',
      audioSrc: 'sounds/chick.mp3',
    },
    {
      id: 6,
      word: 'hamster',
      translation: 'хомяк',
      image: 'img/hamster.png',
      audioSrc: 'sounds/hamster.mp3',
    },
    {
      id: 7,
      word: 'bear',
      translation: 'медведь',
      image: 'img/bear.png',
      audioSrc: 'sounds/bear.mp3',
    },
    'animals',
  ],
  pageFeelings: [
    {
      id: 8,
      word: 'angry',
      translation: 'сердитый',
      image: 'img/angry.png',
      audioSrc: 'sounds/angry.mp3',
    },
    {
      id: 9,
      word: 'sad',
      translation: 'грустный',
      image: 'img/sad.png',
      audioSrc: 'sounds/sad.mp3',
    },
    {
      id: 10,
      word: 'cry',
      translation: 'плачь',
      image: 'img/cry.png',
      audioSrc: 'sounds/cry.mp3',
    },
    {
      id: 11,
      word: 'fright',
      translation: 'страх',
      image: 'img/fright.png',
      audioSrc: 'sounds/fright.mp3',
    },
    {
      id: 12,
      word: 'happy',
      translation: 'счастливый',
      image: 'img/happy.png',
      audioSrc: 'sounds/happy.mp3',
    },
    {
      id: 13,
      word: 'calm',
      translation: 'спокойный',
      image: 'img/calm.png',
      audioSrc: 'sounds/calm.mp3',
    },
    {
      id: 14,
      word: 'surprised',
      translation: 'удивленный',
      image: 'img/surprised.png',
      audioSrc: 'sounds/surprised.mp3',
    },
    {
      id: 15,
      word: 'lazy',
      translation: 'ленивый',
      image: 'img/lazy.png',
      audioSrc: 'sounds/lazy.mp3',
    },
    'feelings',
  ],
  pageClothes: [
    {
      id: 16,
      word: 'bag',
      translation: 'сумка',
      image: 'img/bag.png',
      audioSrc: 'sounds/bag.mp3',
    },
    {
      id: 17,
      word: 'sneaker',
      translation: 'кроссовок',
      image: 'img/sneaker.png',
      audioSrc: 'sounds/sneaker.mp3',
    },
    {
      id: 18,
      word: 'pullover',
      translation: 'свитер',
      image: 'img/pullover.png',
      audioSrc: 'sounds/pullover.mp3',
    },
    {
      id: 19,
      word: 'shoe',
      translation: 'обувь',
      image: 'img/shoe.png',
      audioSrc: 'sounds/shoe.mp3',
    },
    {
      id: 20,
      word: 'coat',
      translation: 'пальто',
      image: 'img/coat.png',
      audioSrc: 'sounds/coat.mp3',
    },
    {
      id: 21,
      word: 'jacket',
      translation: 'куртка',
      image: 'img/jacket.png',
      audioSrc: 'sounds/jacket.mp3',
    },
    {
      id: 22,
      word: 'hat',
      translation: 'шляпа',
      image: 'img/hat.png',
      audioSrc: 'sounds/hat.mp3',
    },
    {
      id: 23,
      word: 'scarf',
      translation: 'шарф',
      image: 'img/scarf.png',
      audioSrc: 'sounds/scarf.mp3',
    },
    'clothes',
  ],
  pageActions: [
    {
      id: 24,
      word: 'sleep',
      translation: 'спать',
      image: 'img/sleep.png',
      audioSrc: 'sounds/sleep.mp3',
    },
    {
      id: 25,
      word: 'read',
      translation: 'читать',
      image: 'img/read.png',
      audioSrc: 'sounds/read.mp3',
    },
    {
      id: 26,
      word: 'wash',
      translation: 'мыться',
      image: 'img/wash.png',
      audioSrc: 'sounds/wash.mp3',
    },
    {
      id: 27,
      word: 'play',
      translation: 'играть',
      image: 'img/play.png',
      audioSrc: 'sounds/play.mp3',
    },
    {
      id: 28,
      word: 'write',
      translation: 'писать',
      image: 'img/write.png',
      audioSrc: 'sounds/write.mp3',
    },
    {
      id: 29,
      word: 'draw',
      translation: 'рисовать',
      image: 'img/draw.png',
      audioSrc: 'sounds/draw.mp3',
    },
    {
      id: 30,
      word: 'cook',
      translation: 'готовить',
      image: 'img/cook.png',
      audioSrc: 'sounds/cook.mp3',
    },
    {
      id: 31,
      word: 'hug',
      translation: 'обнимать',
      image: 'img/hug.png',
      audioSrc: 'sounds/hug.mp3',
    },
    'actions',
  ],
  pageFood: [
    {
      id: 32,
      word: 'bread',
      translation: 'хлеб',
      image: 'img/bread.png',
      audioSrc: 'sounds/bread.mp3',
    },
    {
      id: 33,
      word: 'pie',
      translation: 'пирог',
      image: 'img/pie.png',
      audioSrc: 'sounds/pie.mp3',
    },
    {
      id: 34,
      word: 'donut',
      translation: 'пончик',
      image: 'img/donut.png',
      audioSrc: 'sounds/donut.mp3',
    },
    {
      id: 35,
      word: 'cookie',
      translation: 'печенье',
      image: 'img/cookie.png',
      audioSrc: 'sounds/cookie.mp3',
    },
    {
      id: 36,
      word: 'ice cream',
      translation: 'мороженое',
      image: 'img/ice cream.png',
      audioSrc: 'sounds/ice_cream.mp3',
    },
    {
      id: 37,
      word: 'pasta',
      translation: 'макароны',
      image: 'img/pasta.png',
      audioSrc: 'sounds/pasta.mp3',
    },
    {
      id: 38,
      word: 'meat',
      translation: 'мясо',
      image: 'img/meat.png',
      audioSrc: 'sounds/meat.mp3',
    },
    {
      id: 39,
      word: 'pancake',
      translation: 'блинчик',
      image: 'img/pancake.png',
      audioSrc: 'sounds/pancake.mp3',
    },
    'food',
  ],
  pageWeather: [
    {
      id: 40,
      word: 'autumn',
      translation: 'осень',
      image: 'img/autumn.png',
      audioSrc: 'sounds/autumn.mp3',
    },
    {
      id: 41,
      word: 'winter',
      translation: 'зима',
      image: 'img/winter.png',
      audioSrc: 'sounds/winter.mp3',
    },
    {
      id: 42,
      word: 'spring',
      translation: 'весна',
      image: 'img/spring.png',
      audioSrc: 'sounds/spring.mp3',
    },
    {
      id: 43,
      word: 'summer',
      translation: 'лето',
      image: 'img/summer.png',
      audioSrc: 'sounds/summer.mp3',
    },
    {
      id: 44,
      word: 'umbrella',
      translation: 'зонт',
      image: 'img/umbrella.png',
      audioSrc: 'sounds/umbrella.mp3',
    },
    {
      id: 45,
      word: 'sun',
      translation: 'солнце',
      image: 'img/sun.png',
      audioSrc: 'sounds/sun.mp3',
    },
    {
      id: 46,
      word: 'cold',
      translation: 'холод',
      image: 'img/cold.png',
      audioSrc: 'sounds/cold.mp3',
    },
    {
      id: 47,
      word: 'rain',
      translation: 'дождь',
      image: 'img/rain.png',
      audioSrc: 'sounds/rain.mp3',
    },
    'weather',
  ],
  pageHollydays: [
    {
      id: 48,
      word: 'birthday',
      translation: 'день рождения',
      image: 'img/birthday.png',
      audioSrc: 'sounds/birthday.mp3',
    },
    {
      id: 49,
      word: 'cake',
      translation: 'торт',
      image: 'img/cake.png',
      audioSrc: 'sounds/cake.mp3',
    },
    {
      id: 50,
      word: 'christmas',
      translation: 'рождество',
      image: 'img/christmas.png',
      audioSrc: 'sounds/christmas.mp3',
    },
    {
      id: 51,
      word: 'decoration',
      translation: 'украшение',
      image: 'img/decoration.png',
      audioSrc: 'sounds/decoration.mp3',
    },
    {
      id: 52,
      word: 'halloween',
      translation: 'хелоуин',
      image: 'img/halloween.png',
      audioSrc: 'sounds/halloween.mp3',
    },
    {
      id: 53,
      word: "valentine's day",
      translation: 'день святого валентина',
      image: "img/valentine's day.png",
      audioSrc: "sounds/valentine's_day.mp3",
    },
    {
      id: 54,
      word: 'easter',
      translation: 'пасха',
      image: 'img/easter.png',
      audioSrc: 'sounds/easter.mp3',
    },
    {
      id: 55,
      word: 'gift',
      translation: 'подарок',
      image: 'img/gift.png',
      audioSrc: 'sounds/gift.mp3',
    },
    'hollydays',
  ],
  pageObjects: [
    {
      id: 56,
      word: 'bed',
      translation: 'кровать',
      image: 'img/bed.png',
      audioSrc: 'sounds/bed.mp3',
    },
    {
      id: 57,
      word: 'book',
      translation: 'книга',
      image: 'img/book.png',
      audioSrc: 'sounds/book.mp3',
    },
    {
      id: 58,
      word: 'box',
      translation: 'коробка',
      image: 'img/box.png',
      audioSrc: 'sounds/box.mp3',
    },
    {
      id: 59,
      word: 'phone',
      translation: 'телефон',
      image: 'img/phone.png',
      audioSrc: 'sounds/phone.mp3',
    },
    {
      id: 60,
      word: 'computer',
      translation: 'компьютер',
      image: 'img/computer.png',
      audioSrc: 'sounds/computer.mp3',
    },
    {
      id: 61,
      word: 'car',
      translation: 'машина',
      image: 'img/car.png',
      audioSrc: 'sounds/car.mp3',
    },
    {
      id: 62,
      word: 'flower',
      translation: 'цветок',
      image: 'img/flower.png',
      audioSrc: 'sounds/flower.mp3',
    },
    {
      id: 63,
      word: 'cup',
      translation: 'кружка',
      image: 'img/cup.png',
      audioSrc: 'sounds/cup.mp3',
    },
    'objects',
  ],
};
